### ISSUE TITLE
Learner Node is not working

### ISSUE THREAD

**Issue by MichelDiz** [hypermodeinc/dgraph#9393]
## Describe the bug

Supposedly, the Learner node would be an instance of Dgraph outside of the RAFT Group. There is no in-depth material on the subject. This makes it difficult to effectively test it. However, in theory, we should have an instance that would supposedly be a replica for readonly.

What is still unknown to me is whether the replica would be total for the entire cluster or individual for each group/shard. The second option would be a bit strange. But plausible.

## To Reproduce

I have created a cluster with 1 zero and 3 alphas. After I tried run a Learner Alpha and no luck.

```bash
go run main.go alpha --zero 0.0.0.0:5080 --security "whitelist=0.0.0.0/0;" --my 0.0.0.0:7090 --tmp alphaLearner/t -p=alphaLearner/p -w=alphaLearner/w -o=10 --raft "learner=true;"
```

In order to effectively test it, I had to comment out a line in the code that was forcing a fatal error.
```go
	// if n.RaftContext.IsLearner && !hasPeer {
	// 	glog.Fatal("Cannot start a learner node without peer alpha nodes")
	// }
```
I think the issue here(the fatal one) is due to lack of flag value propagation.

## Expected behavior

To work

## Environment

- OS: macOS
- Language Go
- Version Latest Main - v25.0.0-preview1

## Additional context

Investigations

At this line
https://github.com/hypermodeinc/dgraph/blob/e01eebdf79626aa4cc22d15d910b1fc2b32ba259/worker/groups.go#L96

I saw that the Learner flag was activated.
But in the state it is "learner": false, sounds like the flag is not being propagated.

**Comment by matthewmcneely** [comment]
@MichelDiz Had a look at this today as I was testing this for a client. The TLDR;, the cluster needs a dedicated zero for the learner node. Check out this compose file:

```
# Auto-generated with: [./compose -z=1 -a=3 -n=1 --image dgraph/dgraph -t=local --local=false]
#
version: "3.5"
services:
    alpha1:
        image: dgraph/dgraph:local
        container_name: alpha1
        working_dir: /data/alpha1
        labels:
            cluster: test
        ports:
            - 8180:8180
            - 9180:9180
        command: dgraph alpha -o 100 --my=alpha1:7180 --zero=zero1:5180 --logtostderr -v=2 --raft "idx=1; group=1" --security "whitelist=0.0.0.0/0;"
        deploy:
            resources:
                limits:
                    memory: 32G
    alpha2:
        image: dgraph/dgraph:local
        container_name: alpha2
        working_dir: /data/alpha2
        labels:
            cluster: test
        ports:
            - 8182:8182
            - 9182:9182
        command: dgraph alpha -o 102 --my=alpha2:7182 --zero=zero1:5180 --logtostderr -v=2 --raft "idx=2; group=1" --security "whitelist=0.0.0.0/0;"
        deploy:
            resources:
                limits:
                    memory: 32G
    alpha3:
        image: dgraph/dgraph:local
        container_name: alpha3
        working_dir: /data/alpha3
        labels:
            cluster: test
        ports:
            - 8183:8183
            - 9183:9183
        command: dgraph alpha -o 103 --my=alpha3:7183 --zero=zero1:5180 --logtostderr -v=2 --raft "idx=3; group=1" --security "whitelist=0.0.0.0/0;"
        deploy:
            resources:
                limits:
                    memory: 32G
    alpha4:
        image: dgraph/dgraph:local
        container_name: alpha4
        working_dir: /data/alpha4
        depends_on:
            - alpha3
        labels:
            cluster: test
        ports:
            - 8184:8184
            - 9184:9184
        command: dgraph alpha -o 104 --my=alpha4:7184 --zero=zero1:5180 --logtostderr -v=2 --raft "idx=4; group=1; learner=true" --security "whitelist=0.0.0.0/0;"
        deploy:
            resources:
                limits:
                    memory: 32G
    zero1:
        image: dgraph/dgraph:local
        container_name: zero1
        working_dir: /data/zero1
        labels:
            cluster: test
        ports:
            - 5180:5180
            - 6180:6180
        command: dgraph zero -o 100 --raft='idx=1' --my=zero1:5180 --replicas=3 --logtostderr -v=2 --bindall
        deploy:
            resources:
                limits:
                    memory: 32G
    zero2:
        image: dgraph/dgraph:local
        container_name: zero2
        working_dir: /data/zero2
        depends_on:
            - zero1
        labels:
            cluster: test
        ports:
            - 5182:5182
            - 6182:6182
        command: dgraph zero -o 102 --raft='idx=2; learner=true' --my=zero2:5182 --replicas=3 --logtostderr -v=2 --peer=zero1:5180
        deploy:
            resources:
                limits:
                    memory: 32G
volumes: {}

```

I loaded the 1million movies dataset into this cluster. When connecting Ratel to the Alpha learner, I was able to query successfully.

Please close this if you agree this issue is solved here.
